### ISSUE TITLE
please update readme

### ISSUE THREAD

**Issue by imrepentek** [shift-jis/snake-missile#1]
Hello,

please update your readme with something like you can find an example config file at workspace/config.json and server_address should contain ...

thank you in advance.

**Comment by imrepentek** [comment]
hello, that helped, partially, so do I need chrome or chromium browser? anyhow slither.io does not work for me on either of those browsers -- EDIT: got solved since then, http vs https issue

**Comment by imrepentek** [comment]
also, the browser script refers to port 1337 on localhost which isn't open. is that a bug? do I need to start one more service? if so how?

**Comment by shift-jis** [comment]
When sync_api is started, port 1337 is available.

**Comment by imrepentek** [comment]
can you please point me towards an RTFM detailing how to start sync_api?
Also, what is the format of proxies.txt? is it proto://host:port/ or just host:port? what sort of proxies are supported? http? https? socks4? socks5?

**Comment by shift-jis** [comment]
After installing the package with `npm install`, just run start.bat
The proxy supports `proto://host:port/` and supports http, https, socks5 (not sure about socks4)

**Comment by imrepentek** [comment]
> After installing the package

which package?

>  just run start.bat

I'm on ubuntu linux

**Comment by shift-jis** [comment]
The `npm install` will automatically install the necessary packages, so all you have to do is run index.js using node after installation.

**Comment by imrepentek** [comment]
[README.md](https://github.com/RabiesDev/torpedo/files/12610661/README.md)
I hope I got it right, this would be an easy to follow readme

**Comment by shift-jis** [comment]
We may update the ReadMe to be based on this in due course. Thanks for your help!
